// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: group.sql

package queries

import (
	"context"

	"github.com/kak-tus/irma_bot/model/queries_types"
	"github.com/kak-tus/nan"
	"github.com/lib/pq"
)

const createOrUpdateGroup = `-- name: CreateOrUpdateGroup :exec
INSERT INTO groups
  (id, greeting, questions, ban_url, ban_question, ban_timeout, ignore_domain)
  VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET
  (greeting, questions, ban_url, ban_question, ban_timeout, ignore_domain) =
  ROW(
    EXCLUDED.greeting, EXCLUDED.questions, EXCLUDED.ban_url,
    EXCLUDED.ban_question, EXCLUDED.ban_timeout, EXCLUDED.ignore_domain
    )
`

type CreateOrUpdateGroupParams struct {
	ID           int64
	Greeting     nan.NullString
	Questions    queries_types.QuestionsDB
	BanUrl       nan.NullBool
	BanQuestion  nan.NullBool
	BanTimeout   nan.NullInt32
	IgnoreDomain []string
}

func (q *Queries) CreateOrUpdateGroup(ctx context.Context, arg CreateOrUpdateGroupParams) error {
	_, err := q.db.ExecContext(ctx, createOrUpdateGroup,
		arg.ID,
		arg.Greeting,
		arg.Questions,
		arg.BanUrl,
		arg.BanQuestion,
		arg.BanTimeout,
		pq.Array(arg.IgnoreDomain),
	)
	return err
}

const getGroup = `-- name: GetGroup :one
SELECT
  ban_question,
  ban_url,
  greeting,
  questions,
  ban_timeout,
  ignore_domain
FROM public.groups
WHERE id = $1
`

type GetGroupRow struct {
	BanQuestion  nan.NullBool
	BanUrl       nan.NullBool
	Greeting     nan.NullString
	Questions    queries_types.QuestionsDB
	BanTimeout   nan.NullInt32
	IgnoreDomain []string
}

func (q *Queries) GetGroup(ctx context.Context, id int64) (GetGroupRow, error) {
	row := q.db.QueryRowContext(ctx, getGroup, id)
	var i GetGroupRow
	err := row.Scan(
		&i.BanQuestion,
		&i.BanUrl,
		&i.Greeting,
		&i.Questions,
		&i.BanTimeout,
		pq.Array(&i.IgnoreDomain),
	)
	return i, err
}
