// Code generated by sqlc. DO NOT EDIT.

package queries

import (
	"database/sql"
	"encoding/json"
)

// Group data.
type Group struct {
	// id.
	ID int64
	// Greeting.
	Greeting sql.NullString
	// Questions and answers.
	Questions json.RawMessage
	// Ban by postings urls and forwards.
	BanUrl sql.NullBool
	// Ban by question.
	BanQuestion sql.NullBool
	// Ban delay after question
	BanTimeout sql.NullInt32
}
