// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package queries

import (
	"github.com/kak-tus/irma_bot/model/queries_types"
	"github.com/kak-tus/nan"
)

// Group data.
type Group struct {
	// id.
	ID int64
	// Greeting.
	Greeting nan.NullString
	// Questions and answers.
	Questions queries_types.QuestionsDB
	// Ban by postings urls and forwards.
	BanUrl nan.NullBool
	// Ban by question.
	BanQuestion nan.NullBool
	// Ban delay after question
	BanTimeout     nan.NullInt32
	IgnoreDomain   []string
	BanEmojiiCount nan.NullInt32
}
