// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Answer defines model for Answer.
type Answer struct {
	Correct *bool  `json:"correct,omitempty"`
	Text    string `json:"text"`
}

// Answers defines model for Answers.
type Answers []Answer

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Group defines model for Group.
type Group struct {
	BanQuestion bool      `json:"ban_question"`
	BanTimeout  int32     `json:"ban_timeout"`
	BanUrl      bool      `json:"ban_url"`
	Greeting    string    `json:"greeting"`
	Id          int64     `json:"id"`
	Questions   Questions `json:"questions"`
}

// Healthcheck defines model for Healthcheck.
type Healthcheck map[string]interface{}

// Question defines model for Question.
type Question struct {
	Answers Answers `json:"answers"`
	Text    string  `json:"text"`
}

// Questions defines model for Questions.
type Questions []Question

// TokenData defines model for TokenData.
type TokenData struct {
	Ttl string `json:"ttl"`
}

// Token defines model for Token.
type Token string

// GetGroupResponse defines model for GetGroupResponse.
type GetGroupResponse Group

// GetTokenResponse defines model for GetTokenResponse.
type GetTokenResponse TokenData

// HealthcheckResponse defines model for HealthcheckResponse.
type HealthcheckResponse Healthcheck

// InternalErrorResponse defines model for InternalErrorResponse.
type InternalErrorResponse Error

// NotFoundErrorResponse defines model for NotFoundErrorResponse.
type NotFoundErrorResponse Error

// SaveGroupResponse defines model for SaveGroupResponse.
type SaveGroupResponse map[string]interface{}

// SaveGroupRequest defines model for SaveGroupRequest.
type SaveGroupRequest Group

// GetGroupParams defines parameters for GetGroup.
type GetGroupParams struct {
	Token Token `json:"token"`
}

// SaveGroupParams defines parameters for SaveGroup.
type SaveGroupParams struct {
	Token Token `json:"token"`
}

// GetTokenDataParams defines parameters for GetTokenData.
type GetTokenDataParams struct {
	Token Token `json:"token"`
}

// SaveGroupJSONRequestBody defines body for SaveGroup for application/json ContentType.
type SaveGroupJSONRequestBody SaveGroupRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get group
	// (GET /group)
	GetGroup(w http.ResponseWriter, r *http.Request, params GetGroupParams)
	// Save group
	// (POST /group)
	SaveGroup(w http.ResponseWriter, r *http.Request, params SaveGroupParams)
	// Healthcheck
	// (GET /healthcheck)
	Healthcheck(w http.ResponseWriter, r *http.Request)
	// Get token data
	// (GET /token)
	GetTokenData(w http.ResponseWriter, r *http.Request, params GetTokenDataParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// GetGroup operation middleware
func (siw *ServerInterfaceWrapper) GetGroup(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGroupParams

	// ------------- Required query parameter "token" -------------
	if paramValue := r.URL.Query().Get("token"); paramValue != "" {

	} else {
		http.Error(w, "Query argument token is required, but not found", http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "token", r.URL.Query(), &params.Token)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter token: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGroup(w, r, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// SaveGroup operation middleware
func (siw *ServerInterfaceWrapper) SaveGroup(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SaveGroupParams

	// ------------- Required query parameter "token" -------------
	if paramValue := r.URL.Query().Get("token"); paramValue != "" {

	} else {
		http.Error(w, "Query argument token is required, but not found", http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "token", r.URL.Query(), &params.Token)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter token: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SaveGroup(w, r, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// Healthcheck operation middleware
func (siw *ServerInterfaceWrapper) Healthcheck(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Healthcheck(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetTokenData operation middleware
func (siw *ServerInterfaceWrapper) GetTokenData(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTokenDataParams

	// ------------- Required query parameter "token" -------------
	if paramValue := r.URL.Query().Get("token"); paramValue != "" {

	} else {
		http.Error(w, "Query argument token is required, but not found", http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "token", r.URL.Query(), &params.Token)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter token: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTokenData(w, r, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL     string
	BaseRouter  chi.Router
	Middlewares []MiddlewareFunc
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/group", wrapper.GetGroup)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/group", wrapper.SaveGroup)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthcheck", wrapper.Healthcheck)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/token", wrapper.GetTokenData)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xWS2/bOBD+K8bsHpnITrI56JbF7mYNFEXT9hYEBS2NbSYiqZAjN0ag/16Q1NOS4cB1",
	"i9z0GM73zTecxyskWuZaoSIL8Svk3HCJhMa/fdVPqNyDUBDDc4FmCwwUlwgxkP/JwOBzIQymEJMpkIFN",
	"1ii5O0Xb3BlaMkKtoCzLYIyW/tapQA/xhW/w1ugi/xz+uG+JVoTKP/I8z0TCSWgVPVrtybQAfxpcQgx/",
	"RG0QUfhrI++0BW0Zhi8218oGCrdIFYPw8fQUSuZAvJonB/Fe/+HEK6D/kWe0TtaYPJ0cq+O7QpsrQqN4",
	"9q8x2pwcz3utkD5q+k8XKv31SJ0reQRKden14hET8h7Luib8bbtR9jsaX2tG52ioKoREG+NOtC4WWmfI",
	"FZQMCF/8H8lfPqBa0Rri2XTKQArVvLNBvXVv/n3w8cB2CbKKkSchCKU9pFUVQckcnXk4MQtk6rcGhRvD",
	"t840CDyIWqK1fIVj3aLPvjYcCyDU2cD3gqtvvqeIkKOhrM6ChERdeHWX2khOEINQdHkBPj4hCwnxdQgv",
	"vLTRCUW4ClI4V4XJxnFWBpFcVIMUHsohA5HuUru+gjEGdagH83fXGO6KLFLokGV9BdsY+8J1kcey020a",
	"w/pgcNdJUT+BvL2Yh++j3V8nxxQKa9DHYrrrav2mommi3CmbQ3XTtveBPERZ72qknPBsKSTCwQgpGwnL",
	"WQm11M5pijYxIg95gZtPc+dTUObs50byyULTZGl8U0wn4f8GjQ32s/Pp+dSx1zkqnguI4dJ/YpBzWnv2",
	"0aqu2hX6nLnQfFOdpxA3Q9kfaXeS+3GVW5MwD6F82BnyF9PpvhQ1dtFgEygZXE2vDh8cH04lg7/eAjs+",
	"RP3cKKTkZhv0mATFSga5tiOSNXPrpzSr97Ptft6dFS4a7G/lMcIPR+77Ud5xq6UvGUTrfj8bvb3dnneM",
	"HmNLXJ9VfxVjEFG9q+8rp7aT/OaS6u+976ukvGqTtFqfGVg0m1oVP85hTZTbOIqEkfxsoemcniKei2gz",
	"g/Kh/BEAAP//E5uAjUANAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
